"""Final migration

Revision ID: 589a52777dc0
Revises: 661fc4ca69a6
Create Date: 2021-08-15 13:55:29.492482

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '589a52777dc0'
down_revision = '661fc4ca69a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_insolvency_case', table_name='insolvencies')
    op.drop_index('ix_insolvency_ico', table_name='insolvencies')
    op.drop_index('ix_insolvency_state', table_name='insolvencies')
    op.create_index(op.f('ix_insolvencies_case'), 'insolvencies', ['case'], unique=False)
    op.create_index(op.f('ix_insolvencies_ico'), 'insolvencies', ['ico'], unique=False)
    op.create_index(op.f('ix_insolvencies_state'), 'insolvencies', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insolvencies_state'), table_name='insolvencies')
    op.drop_index(op.f('ix_insolvencies_ico'), table_name='insolvencies')
    op.drop_index(op.f('ix_insolvencies_case'), table_name='insolvencies')
    op.create_index('ix_insolvency_state', 'insolvencies', ['state'], unique=False)
    op.create_index('ix_insolvency_ico', 'insolvencies', ['ico'], unique=False)
    op.create_index('ix_insolvency_case', 'insolvencies', ['case'], unique=False)
    # ### end Alembic commands ###
