"""Added token to users for api implementation

Revision ID: 86efb051419a
Revises: 2a95f956edbd
Create Date: 2021-08-01 22:17:54.248086

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '86efb051419a'
down_revision = '2a95f956edbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
