"""empty message

Revision ID: 95f9248a484b
Revises: 
Create Date: 2021-07-26 10:53:50.190021

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '95f9248a484b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insolvency',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ico', sa.String(length=8), nullable=True),
                    sa.Column('case', sa.String(length=10), nullable=True),
                    sa.Column('year', sa.Integer(), nullable=True),
                    sa.Column('senate_number', sa.Integer(), nullable=True),
                    sa.Column('ordering_org', sa.String(length=100), nullable=True),
                    sa.Column('state', sa.String(length=40), nullable=True),
                    sa.Column('url', sa.String(length=128), nullable=True),
                    sa.Column('bankruptcy_start', sa.Date(), nullable=True),
                    sa.Column('bankruptcy_end', sa.Date(), nullable=True),
                    sa.Column('claimed', sa.Boolean(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_insolvency_case'), 'insolvency', ['case'], unique=False)
    op.create_index(op.f('ix_insolvency_ico'), 'insolvency', ['ico'], unique=False)
    op.create_index(op.f('ix_insolvency_state'), 'insolvency', ['state'], unique=False)
    op.create_table('partners',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('ico', sa.String(length=8), nullable=True),
                    sa.Column('dic', sa.String(length=20), nullable=True),
                    sa.Column('name', sa.String(length=128), nullable=True),
                    sa.Column('state', sa.String(length=30), nullable=True),
                    sa.Column('business_start', sa.Date(), nullable=True),
                    sa.Column('business_end', sa.Date(), nullable=True),
                    sa.Column('business_form', sa.String(length=50), nullable=True),
                    sa.Column('street', sa.String(length=128), nullable=True),
                    sa.Column('street_number', sa.String(length=6), nullable=True),
                    sa.Column('orientation_number', sa.String(length=6), nullable=True),
                    sa.Column('city_part', sa.String(length=128), nullable=True),
                    sa.Column('city', sa.String(length=128), nullable=True),
                    sa.Column('zip_code', sa.String(length=5), nullable=True),
                    sa.Column('country', sa.String(length=128), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_partners_ico'), 'partners', ['ico'], unique=True)
    op.create_index(op.f('ix_partners_name'), 'partners', ['name'], unique=False)
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=64), nullable=True),
                    sa.Column('first_name', sa.String(length=64), nullable=True),
                    sa.Column('last_name', sa.String(length=64), nullable=True),
                    sa.Column('password', sa.String(length=128), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('modified', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('partner2insolvency',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('partner_id', sa.Integer(), nullable=True),
                    sa.Column('insolvency_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['insolvency_id'], ['insolvency.id'], ),
                    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user2partner',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('partner_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user2partner')
    op.drop_table('partner2insolvency')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_partners_name'), table_name='partners')
    op.drop_index(op.f('ix_partners_ico'), table_name='partners')
    op.drop_table('partners')
    op.drop_index(op.f('ix_insolvency_state'), table_name='insolvency')
    op.drop_index(op.f('ix_insolvency_ico'), table_name='insolvency')
    op.drop_index(op.f('ix_insolvency_case'), table_name='insolvency')
    op.drop_table('insolvency')
    # ### end Alembic commands ###
